### PR TITLE
WIP First public release

### PR DESCRIPTION
**Pull request by dset0x**
Things that are on the way are tests to stabilize use of redis and changes of
pytest 2.8, the checks that we will be bundling with the suite themselves and
some front-end features and fixes.

(And yes, the commits will be reworded in time)

cc @kaplun @Dziolas

### CODE REVIEW

**Comment by kaplun** [comment]
@dset0x would be great if you can make Travis to pass

**Comment by dset0x** [comment]
@kaplun Unfortunately the checker is now stuck in dependency issues. (Right now it's `InvocationError: '/home/gs-sis/.virtualenvs/invenio/src/invenio-checker/.tox/py27/bin/python setup.py test'`)

For future reference, here's a `pip freeze` of my virtualenv at the moment: https://gist.github.com/dset0x/9bb40a2467fa868d9788

**Comment by kaplun** [comment]
@dset0x, have you applied latest cookiecutter template?

**Comment by dset0x** [comment]
This is presently on a4f8f27b809c3fa5e6336760d35979959e4f4402 of that template.

**Comment by kaplun** [comment]
Just asking because if I am not mistaken cookicutter doesn't use tox anymore.

**Comment by kaplun** [comment]
@dset0x how are you? If you are still available, with some spare time, would you be able to make Travis to work, so that we have a working instance of invenio-checker and we can start using it?

Ciao!

**Comment by dset0x** [comment]
Hello @kaplun. Unfortunately, because of troubles that I had with setting up a working virtualenv and due to how soon I have to leave now, I'm afraid I won't be able to get this bit sorted out.

**Comment by kaplun** [comment]
Yep this PR should be ported to Invenio 3 (cc @inspirehep/core)

**Comment by kaplun** [comment]
@david-caro this is another mega-monster project that was implemented on Invenio 2 and requires a bit of love in order to port it to Invenio3.

It has less priority than the others but at might be useful to have it integrated some day.

**Comment by kaplun** [comment]
I am just merging this so that it is easier to check if it's possible to work on it and port it to Invenio 3.

**Pull request merged**
